[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.regex]
target = "functions/button_callbacks.lua"
pattern = "0,(math\\.floor\\(.+?\\)\\))"
position = "at"
line_prepend = ""
payload = "0, math.min($1, 30)"
