[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "G.ARGS.score_intensity.earned_score = G.GAME.current_round.current_hand.chips*G.GAME.current_round.current_hand.mult"
position = "after"
payload = '''
if G.ARGS.score_intensity.earned_score == math.huge then
    G.ARGS.score_intensity.earned_score = 1e308
end
'''
match_indent = true
overwrite = false